### ISSUE TITLE
Uncaught TypeError: Cannot read property 'JS_RequestInterface' of undefined

### ISSUE THREAD

**Issue by manhere** [Ezviz-OpenBiz/EZUIKit-JavaScript-HD#1]
`
ezuikit-hd.js:342 Uncaught TypeError: Cannot read property 'JS_RequestInterface' of undefined
    at EZUIKitHd.init (ezuikit-hd.js:342)
`

**Comment by tianxiubo63** [comment]
add a delay times between new and init function
   var EZUIKitHd = new EZUIKitHd({
      id: 'playWnd',
      layout: 2,
    })
            setTimeout(function () {
                ezuikitHd.init({
                    accessToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
                    layout: 2,
                    videoType: 0,
                });
            },800);

**Comment by tianxiubo63** [comment]
add a delay times between new and init function
`
var EZUIKitHd = new EZUIKitHd({
    id: 'playWnd',
    layout: 2,
})
setTimeout(function () {
    ezuikitHd.init({
        accessToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
        layout: 2,
        videoType: 0,
});
 },800);
`
